@startuml stan-loop 

skinparam defaultFontName Monospace

state "**stan run**" as Run
Run: - review & edit code
Run: - cmd: **""stan run""**
Run: - cmd: **""git commit""**

state "**stan snap**" as Snap
Snap: - upload outputs
Snap: - cmd: **""stan snap""**

state "**stan patch**" as Patch
Patch: - discuss requirements
Patch: - execute dev plan
Patch: - copy patches + commit msg
Patch: - cmd: **""stan patch""**

state "release" as Release

state Done <<choice>>

[*] -right-> Run: start\nhere

Run -right-> Done: code archived\ntypecheck/lint/test/etc\noutputs packaged
Done -right-> Release : scripts green\ncode complete
Release -right-> [*] : done
Done -down-> Snap : scripts not green\noutstanding questions
Snap -left-> Patch : diff\nbaselined
note top on link
    requirements, 
    dev plan & history
    version controlled
    & patched as code
end note
Patch -up-> Run : patches\napplied



@enduml
